; Curated GTA Online road vehicles. Weaponized/special vehicles are intentionally excluded.

[Compact]
asbo
brioso
brioso2
brioso3
club
issi3
kanjo
weevil

[Sedan]
cinquemila
cognoscenti
deity
glendale2
greenwood
komoda
minimus
rhinehart
schafter4
stafford
tailgater2

[SUV]
aleutian
astron
baller4
baller7
baller8
cavalcade3
granger2
iwagen
jubilee
landstalker2
novak
rebla
seminole2
toros
vivanite

[Coupe]
eurosx32
fr36
kanjosj
postlude
previon
windsor
windsor2

[Muscle]
buffalo4
buffalo5
clique
clique2
deviant
dominator3
dominator7
dominator8
dominator9
gauntlet3
gauntlet4
gauntlet5
hermes
impaler
impaler6
ruiner4
tampa4
tulip
tulip2
vigero2
vigero3
weevil2

[Sports]
comet6
comet7
coquette4
cypher
euros
growler
italirsx
jester3
jester5
jugular
neo
omnisegt
panthere
paragon
penumbra2
rt3000
schlagen
sentinel5
sugoi
tenf
vectre
vstr
zr350

[Luxury]
adder
cheetah3
emerus
entity2
entity3
envisage
gp1
ignus
nero
osiris
penetrator
pfister811
reaper
suzume
t20
tempesta
thrax
torero2
turismo2
turismo3
tyrus
xa21
zeno
zentorno
zorrusso

[Pickup]
caracara2
contender
everon
everon3
firebolt
l35
yosemite3
yosemite1500

[Van]
burrito4
minivan2
paradise
rumpo3
speedo4
youga3
youga4

[Offroad]
boor
caracara3
dubsta3
freecrawler
hellion
kamacho
monstrociti
outlaw
patriot3
ratel
terminus
vagrant
verus

[Lowrider]
buccaneer2
chino2
faction2
faction3
moonbeam2
peyote3
slamvan3
tornado5
voodoo

[Industrial]
benson2
boxville4
flatbed2
keitora
mule3
pounder2
stockade4
